spring:
  profiles: dev
general:
  mongodb:
    masterdb: master
    servers:
      - ip: localhost
        port: 27017
  microservices:
    aa: http://localhost:8081/aa/

  jwt:
    keyId: NGLKeyAuth
    issuer: Bheaver Inc
    audience: NGL Client
    expirationTimeInMins: 30
    subject: NGL Client Authorization Token
    email: sid.errabolu@gmail.com